localStorage.setItem(
  "users",
  JSON.stringify([
    {
      userId: 1398827,
      userName: "hung",
      userEmail: "nguyenhung0172004@gmail.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398828,
      userName: "user2",
      userEmail: "user2@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398829,
      userName: "user3",
      userEmail: "user3@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398830,
      userName: "user4",
      userEmail: "user4@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398831,
      userName: "user5",
      userEmail: "user5@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398832,
      userName: "user6",
      userEmail: "user6@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398833,
      userName: "user7",
      userEmail: "user7@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398834,
      userName: "user8",
      userEmail: "user8@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
    {
      userId: 1398835,
      userName: "user9",
      userEmail: "user9@example.com",
      userPasWord: "123456",
      off: false,
      donhang: [],
    },
  ])
);
